# Generated by Django 4.1.6 on 2023-10-20 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=25)),
                ('AGE', models.IntegerField(null=True)),
                ('DATE_OF_BIRTH', models.DateField()),
                ('GENDER', models.CharField(choices=[('o', '------'), ('m', 'Male'), ('f', 'Female')], default='o', max_length=1)),
                ('MAIL_ID', models.EmailField(blank=True, max_length=254, null=True)),
                ('PHONE_NUMBER', models.CharField(blank=True, max_length=15, null=True)),
                ('ADDRESS', models.TextField(default='', null=True)),
                ('ACCOUNT_TYPE', models.CharField(choices=[('n', '------'), ('s', 'savings Account'), ('c', 'current Account')], default='n', max_length=1)),
                ('MATERIALS_PROVIDED', models.CharField(choices=[('Nn', 'None'), ('d', 'debit Card'), ('cr', 'credit Card'), ('ch', 'cheque Book')], default='Nn', max_length=2)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proapp.branch')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proapp.district')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proapp.district'),
        ),
    ]
